# Generated by Django 3.0.4 on 2020-03-30 15:46

from django.db import migrations, models
import django.db.models.deletion
import wehouse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('UID', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='UID')),
                ('Uname', models.CharField(max_length=45, verbose_name='Uname')),
                ('Unation', models.CharField(max_length=45, verbose_name='Unation')),
                ('Ugender', models.CharField(max_length=45, verbose_name='Ugender')),
                ('Uage', models.CharField(max_length=45, verbose_name='Uage')),
                ('Ulis_kind', models.CharField(max_length=45, verbose_name='Ulis_kind')),
                ('Ulis_num', models.CharField(max_length=45, verbose_name='Ulis_num')),
                ('Ucontent', models.CharField(max_length=45, verbose_name='Ucontent')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('HID', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='HID')),
                ('Hname', models.CharField(max_length=45, verbose_name='Hname')),
                ('Hprice', models.CharField(max_length=45, verbose_name='Hprice')),
                ('Haddress', models.CharField(max_length=100, verbose_name='Haddress')),
                ('Hcontect', models.CharField(max_length=45, verbose_name='Hcontect')),
                ('Hdecoration', models.CharField(max_length=45, verbose_name='Hdecoration')),
                ('Hkind', models.CharField(max_length=45, verbose_name='Hkind')),
                ('Hnature', models.CharField(max_length=45, verbose_name='Hnature')),
                ('Harea', models.CharField(max_length=45, verbose_name='Harea')),
                ('Hcover_area', models.CharField(max_length=45, verbose_name='Hcover_area')),
                ('Hgift', models.CharField(max_length=45, verbose_name='Hgift')),
                ('PID', models.CharField(max_length=15, verbose_name='PID')),
                ('CID', models.CharField(max_length=15, verbose_name='CID')),
                ('VID', models.CharField(max_length=15, verbose_name='VID')),
                ('Hpic', models.ImageField(blank=True, upload_to=wehouse.models.custom_path, verbose_name='Hpic')),
                ('Howner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wehouse.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bstatus', models.CharField(max_length=45, verbose_name='Bstatus')),
                ('Btime', models.DateTimeField(auto_now_add=True, verbose_name='Btime')),
                ('Btime_after', models.DateTimeField(verbose_name='Btime_after')),
                ('Bprice', models.CharField(max_length=45, verbose_name='Bprice')),
                ('Bcost', models.CharField(max_length=45, verbose_name='Bcost')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wehouse.House')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wehouse.Customers')),
            ],
        ),
    ]
