# Generated by Django 3.0.4 on 2020-03-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id',
        ),
        migrations.AddField(
            model_name='business',
            name='BID',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False, verbose_name='BID'),
        ),
    ]
