# Generated by Django 3.0.4 on 2020-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehouse', '0003_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='UID',
            field=models.CharField(max_length=45, unique=True, verbose_name='UID'),
        ),
    ]
