# Generated by Django 3.0.4 on 2020-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehouse', '0004_auto_20200403_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Btime_after',
            field=models.CharField(max_length=45, verbose_name='Btime_after'),
        ),
    ]
