# Generated by Django 3.0.4 on 2020-04-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehouse', '0005_auto_20200419_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='staff',
            field=models.IntegerField(default=0),
        ),
    ]
