# Generated by Django 3.0.4 on 2020-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wehouse', '0006_customers_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='HOT',
            field=models.IntegerField(default=0),
        ),
    ]
